apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-minio
  labels:
    app: doc-minio
    tier: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc-minio
  template:
    metadata:
      labels:
        app: doc-minio
        tier: service
    spec:
      containers:
        - name: doc-minio-service
          image: hcmusdoc/prj-doc-minio:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: doc-minio-secret
                  key: minio-user

            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doc-minio-secret
                  key: minio-password

            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: doc-const-config
                  key: vietnam-timezone
          volumeMounts:
            - mountPath: /data
              name: doc-minio-volume

      volumes:
        - name: doc-minio-volume
          persistentVolumeClaim:
            claimName: doc-minio-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: doc-minio
  labels:
    app: doc-minio
    tier: service
spec:
  selector:
    app: doc-minio
  ports:
    - port: 9000
      targetPort: 9000
      name: minio-api
    - port: 9001
      targetPort: 9001
      name: minio-console
