package edu.hcmus.doc.mainservice.model.enums;

public enum MESSAGE {
  submit_document_to_giam_doc_type_label,
  submit_document_to_giam_doc_menu_label,
  transfer_document_to_giam_doc_type_label,
  transfer_document_to_giam_doc_menu_label,
  assign_document_to_truong_phong_type_label,
  assign_document_to_truong_phong_menu_label,
  transfer_document_to_truong_phong_type_label,
  transfer_document_to_truong_phong_menu_label,
  transfer_document_to_van_thu_type_label,
  transfer_document_to_van_thu_menu_label,
  assign_document_to_chuyen_vien_type_label,
  assign_document_to_chuyen_vien_menu_label,
  transfer_document_to_chuyen_vien_type_label,
  transfer_document_to_chuyen_vien_menu_label,
  user_has_already_exists_in_the_flow_of_document,
  user_not_have_permission_to_transfer_document_in_same_level,
  user_not_have_permission_to_transfer_this_document,
  infinite_processing_duration,
}
