SET SEARCH_PATH TO doc_main;

ALTER TABLE INCOMING_DOCUMENT ALTER COLUMN IS_DELETED DROP NOT NULL;
ALTER TABLE INCOMING_DOCUMENT ALTER COLUMN SENDING_LEVEL_ID DROP NOT NULL;
ALTER TABLE INCOMING_DOCUMENT ALTER COLUMN FOLDER DROP NOT NULL;
